[advisories]

[licenses]
allow = [
    "Apache-2.0",
    "MIT",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "MPL-2.0",
    "ISC",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "AGPL-3.0-only",
    "0BSD",
    "CDLA-Permissive-2.0",
    "Zlib",
]

[bans]
multiple-versions = "warn"
wildcards = "deny"
