#!/usr/bin/env bash
# scripts/tests/attribution-key.test.sh — tests for scripts/attribution-key.sh
# (audit 2026-08-28 §4.8#10).
#
# The key is the deliverable, so the suite must prove the OLD key is wrong on
# the release's own edit — not just that the new one is stable, which a constant
# would also satisfy.
#
# The defect: `make notice` stored `sha256sum Cargo.lock` and `make notice-check`
# compared against it. The workspace's own packages are entries in that file, so
# a release version bump changed the hash and failed the legal-attribution gate
# with nothing attributable to regenerate.
#
# Usage: bash scripts/tests/attribution-key.test.sh

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
KEY="${SCRIPT_DIR}/attribution-key.sh"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

failures=0
pass() { echo "  ok   — $*"; }
fail() { echo "  FAIL — $*"; failures=$((failures + 1)); }

# A miniature Cargo.lock: two third-party packages and the two workspace
# members, which carry no `source` line — exactly as cargo writes them.
cat > "${TMP}/base.lock" <<'EOF'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "aho-corasick"
version = "1.1.3"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "8e60d3430d3a69478ad0993f19238d2df97c507009a52b3c10addcd7f6bcb916"

[[package]]
name = "hearth"
version = "1.6.11"
dependencies = [
 "aho-corasick",
 "zeroize",
]

[[package]]
name = "hearth-simulation"
version = "1.6.11"
dependencies = [
 "hearth",
]

[[package]]
name = "zeroize"
version = "1.8.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "ced3678a2879b30306d323f4542626697a464a97c0a07c9aebf7ebca65cd4dde"
EOF

BASE="$(bash "$KEY" "${TMP}/base.lock")"

# variant <name> <sed-expression>
variant() {
    sed "$2" "${TMP}/base.lock" > "${TMP}/$1.lock"
    bash "$KEY" "${TMP}/$1.lock"
}

echo "== the release's own version bump must NOT change the key (the defect) =="
# Bump both workspace members, exactly as a release does.
sed -e '/name = "hearth"/{n;s/version = "1.6.11"/version = "1.7.0"/;}' \
    -e '/name = "hearth-simulation"/{n;s/version = "1.6.11"/version = "1.7.0"/;}' \
    "${TMP}/base.lock" > "${TMP}/bumped.lock"

old_base="$(sha256sum "${TMP}/base.lock" | awk '{print $1}')"
old_bumped="$(sha256sum "${TMP}/bumped.lock" | awk '{print $1}')"
if [[ "$old_base" == "$old_bumped" ]]; then
    fail "the whole-file hash is unchanged by a version bump; this fixture no longer reproduces §4.8#10"
else
    pass "the pre-fix whole-file hash DOES change on a version bump — the reported defect"
fi

if [[ "$(bash "$KEY" "${TMP}/bumped.lock")" == "$BASE" ]]; then
    pass "the attribution key is unchanged by the workspace's own version bump"
else
    fail "the attribution key changed on a workspace version bump"
fi

echo "== anything that changes attribution MUST change the key =="

got="$(variant thirdparty-version '/name = "zeroize"/{n;s/version = "1.8.1"/version = "1.9.0"/;}')"
[[ "$got" != "$BASE" ]] && pass "a third-party version bump" || fail "a third-party version bump did not change the key"

got="$(variant checksum 's/ced3678a2879b30306d323f4542626697a464a97c0a07c9aebf7ebca65cd4dde/0000000000000000000000000000000000000000000000000000000000000000/')"
[[ "$got" != "$BASE" ]] && pass "a changed checksum" || fail "a changed checksum did not change the key"

got="$(variant registry 's|registry+https://github.com/rust-lang/crates.io-index|git+https://example.invalid/zeroize|')"
[[ "$got" != "$BASE" ]] && pass "a different source registry" || fail "a different source registry did not change the key"

got="$(variant removed '/^name = "zeroize"$/,+3d')"
[[ "$got" != "$BASE" ]] && pass "a removed third-party package" || fail "a removed third-party package did not change the key"

cat "${TMP}/base.lock" > "${TMP}/added.lock"
cat >> "${TMP}/added.lock" <<'EOF'

[[package]]
name = "brand-new-crate"
version = "0.1.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "1111111111111111111111111111111111111111111111111111111111111111"
EOF
got="$(bash "$KEY" "${TMP}/added.lock")"
[[ "$got" != "$BASE" ]] && pass "an added third-party package" || fail "an added third-party package did not change the key"

echo "== an edge-only change must NOT change the key =="
# Re-point a dependency edge between packages that are all still in the
# lockfile. Verified on this branch: exactly this shape of churn (removing
# reqwest and aws-lc-rs from the build) left `cargo about generate`
# byte-identical while the whole-file hash had already gone red.
awk '
    { print }
    /^checksum = "8e60d3430d3a69478ad0993f19238d2df97c507009a52b3c10addcd7f6bcb916"$/ {
        print "dependencies = ["
        print " \"zeroize\","
        print "]"
    }
' "${TMP}/base.lock" > "${TMP}/edges.lock"

if [[ "$(diff -q "${TMP}/base.lock" "${TMP}/edges.lock" >/dev/null; echo $?)" != "1" ]]; then
    fail "the edge fixture is identical to the base; it proves nothing"
elif [[ "$(bash "$KEY" "${TMP}/edges.lock")" == "$BASE" ]]; then
    pass "a re-pointed dependency edge does not change the key"
else
    fail "a re-pointed dependency edge changed the key"
fi

if bash "$KEY" --packages "${TMP}/base.lock" | grep -q 'dependencies'; then
    fail "dependency edges reached the hashed set"
else
    pass "dependency edges do not reach the hashed set"
fi

echo "== only name, version, source and checksum are hashed =="
if bash "$KEY" --packages "${TMP}/base.lock" \
    | grep -vE '^(name|version|source|checksum) = |^$' | grep -q .; then
    fail "a line other than name/version/source/checksum reached the hashed set"
else
    pass "nothing but name, version, source and checksum is hashed"
fi

echo "== only workspace members are excluded =="
names="$(bash "$KEY" --packages "${TMP}/base.lock" | grep -c '^name = ')"
if [[ "$names" == "2" ]]; then
    pass "2 of 4 packages hashed — the two with a source line"
else
    fail "hashed ${names} packages, want 2"
fi
if bash "$KEY" --packages "${TMP}/base.lock" | grep -q 'name = "hearth'; then
    fail "a workspace member reached the hashed set"
else
    pass "neither workspace member reached the hashed set"
fi

echo "== a new workspace member is excluded automatically =="
cat "${TMP}/base.lock" > "${TMP}/newmember.lock"
cat >> "${TMP}/newmember.lock" <<'EOF'

[[package]]
name = "hearth-tools"
version = "1.6.11"
dependencies = [
 "hearth",
]
EOF
if [[ "$(bash "$KEY" "${TMP}/newmember.lock")" == "$BASE" ]]; then
    pass "a new path package does not change the key"
else
    fail "a new path package changed the key"
fi

echo "== the key is deterministic and well-formed =="
if [[ "$BASE" == "$(bash "$KEY" "${TMP}/base.lock")" ]]; then
    pass "two runs agree"
else
    fail "two runs disagree"
fi
if [[ "$BASE" =~ ^[0-9a-f]{64}$ ]]; then
    pass "the key is a 64-character hex digest"
else
    fail "the key is not a 64-character hex digest: '${BASE}'"
fi

echo "== a missing lockfile is refused, not hashed =="
out="$(bash "$KEY" "${TMP}/absent.lock" 2>&1)"; rc=$?
if [[ "$rc" == "1" ]] && printf '%s' "$out" | grep -q 'not found'; then
    pass "a missing lockfile exits 1"
else
    fail "a missing lockfile: exit ${rc}, output '${out}'"
fi

echo "== the checked-in key matches the checked-in lockfile =="
stored="$(awk '{print $1}' "${REPO_ROOT}/THIRD_PARTY_LICENSES.sha256")"
current="$(bash "$KEY" "${REPO_ROOT}/Cargo.lock")"
if [[ "$stored" == "$current" ]]; then
    pass "THIRD_PARTY_LICENSES.sha256 is current"
else
    fail "THIRD_PARTY_LICENSES.sha256 is stale: stored ${stored}, current ${current}. Run 'make notice'."
fi

echo
if [[ "$failures" -eq 0 ]]; then
    echo "attribution-key: all checks passed"
    exit 0
fi
echo "attribution-key: ${failures} check(s) failed"
exit 1
