#!/usr/bin/env node
// End-to-end SAML 2.0 demo against a running Hearth.
//
// Expects Hearth running at http://localhost:8420 with the bundled
// hearth.yaml. run.sh handles boot + teardown; when iterating by hand,
// start Hearth separately then `node demo.mjs`.
//
// Hearth is a SAML service provider: it consumes assertions from an
// upstream IdP. (It does not act as a SAML IdP — removed in 3.0.0.)
//
// Two acts:
//   1. Fetch Hearth's SP-side metadata (proves the SP metadata endpoint
//      serves the configured ACS URL + our signing cert).
//   2. Impersonate the external IdP: sign a <Response> with the test
//      IdP key, POST it to Hearth's ACS. Then verify an audit event
//      landed with action=SamlLoginCompleted.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { randomBytes } from "node:crypto";
import { DOMParser } from "@xmldom/xmldom";
import { SignedXml } from "xml-crypto";
import forge from "node-forge";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const HEARTH = "http://localhost:8420";
const REALM = "demo";
const CRED_FILE = path.join(__dirname, ".idp-cred.json");
const IDP_ENTITY_ID = "http://localhost:9190/saml/metadata";
const ok = (s) => `\x1b[32m✔\x1b[0m ${s}`;
const step = (s) => console.log(`\n\x1b[1m▸\x1b[0m ${s}`);

// ─── shared: load the test-IdP keypair generated by run.sh ───────────
function loadIdpCredential() {
  if (!fs.existsSync(CRED_FILE)) {
    throw new Error(
      `missing ${CRED_FILE} — run.sh generates this before starting Hearth`,
    );
  }
  const { privateKeyPem, certificatePem } = JSON.parse(
    fs.readFileSync(CRED_FILE, "utf8"),
  );
  return { privateKeyPem, certificatePem };
}

// ─── SAML Response signing (via xml-crypto) ──────────────────────────
function signSamlResponse(xml, privateKeyPem, certificatePem, elementId) {
  const sig = new SignedXml({
    privateKey: privateKeyPem,
    signatureAlgorithm: "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256",
    canonicalizationAlgorithm: "http://www.w3.org/2001/10/xml-exc-c14n#",
  });
  sig.addReference({
    xpath: `//*[@ID='${elementId}']`,
    digestAlgorithm: "http://www.w3.org/2001/04/xmlenc#sha256",
    transforms: [
      "http://www.w3.org/2000/09/xmldsig#enveloped-signature",
      "http://www.w3.org/2001/10/xml-exc-c14n#",
    ],
  });
  const certBody = certificatePem
    .replace(/-----BEGIN CERTIFICATE-----/g, "")
    .replace(/-----END CERTIFICATE-----/g, "")
    .replace(/\s+/g, "");
  sig.getKeyInfoContent = () =>
    `<X509Data><X509Certificate>${certBody}</X509Certificate></X509Data>`;
  sig.computeSignature(xml, {
    prefix: "ds",
    location: { reference: `//*[@ID='${elementId}']`, action: "prepend" },
  });
  return sig.getSignedXml();
}

function buildUnsignedResponse({
  responseId,
  assertionId,
  inResponseTo,
  destination,
  issuer,
  audience,
  nameId,
  sessionIndex,
  now = new Date(),
}) {
  const issueInstant = now.toISOString();
  const notBefore = new Date(now.getTime() - 60_000).toISOString();
  const notOnOrAfter = new Date(now.getTime() + 300_000).toISOString();
  return `<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="${responseId}" Version="2.0" IssueInstant="${issueInstant}" Destination="${destination}" InResponseTo="${inResponseTo}"><saml:Issuer>${issuer}</saml:Issuer><samlp:Status><samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/></samlp:Status><saml:Assertion ID="${assertionId}" Version="2.0" IssueInstant="${issueInstant}"><saml:Issuer>${issuer}</saml:Issuer><saml:Subject><saml:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">${nameId}</saml:NameID><saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer"><saml:SubjectConfirmationData NotOnOrAfter="${notOnOrAfter}" Recipient="${destination}" InResponseTo="${inResponseTo}"/></saml:SubjectConfirmation></saml:Subject><saml:Conditions NotBefore="${notBefore}" NotOnOrAfter="${notOnOrAfter}"><saml:AudienceRestriction><saml:Audience>${audience}</saml:Audience></saml:AudienceRestriction></saml:Conditions><saml:AuthnStatement AuthnInstant="${issueInstant}" SessionIndex="${sessionIndex}"><saml:AuthnContext><saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef></saml:AuthnContext></saml:AuthnStatement></saml:Assertion></samlp:Response>`;
}

// ─── Act 1: SP metadata roundtrip ────────────────────────────────────
async function act1_fetchSpMetadata() {
  step("Act 1 — fetch Hearth's SP metadata");
  const url = `${HEARTH}/ui/realms/${REALM}/federation/saml/metadata?idp=local-idp`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`metadata HTTP ${res.status}`);
  const xml = await res.text();
  if (!xml.includes("SPSSODescriptor"))
    throw new Error("metadata missing SPSSODescriptor");
  if (!xml.includes("AssertionConsumerService"))
    throw new Error("metadata missing AssertionConsumerService");
  console.log(ok(`SP metadata served (${xml.length} bytes)`));
  const doc = new DOMParser().parseFromString(xml);
  const acs = doc
    .getElementsByTagName("md:AssertionConsumerService")[0]
    ?.getAttribute("Location");
  console.log(`  ACS URL: ${acs}`);
  return acs;
}

// ─── Act 2: Fake IdP → Hearth SP ACS ─────────────────────────────────
async function act2_postAssertionToAcs({ privateKeyPem, certificatePem }, acsUrlFromMetadata) {
  step("Act 2 — fake IdP issues a signed Response to Hearth's ACS");

  // 2a. Have Hearth build an AuthnRequest so we get a valid RelayState
  //     back that the ACS will accept. Hearth redirects (302/303/307)
  //     to the IdP SSO URL; we parse the RelayState out of Location.
  const beginUrl = `${HEARTH}/ui/realms/${REALM}/federation/saml/begin?idp=local-idp`;
  const beginRes = await fetch(beginUrl, { redirect: "manual" });
  if (beginRes.status < 300 || beginRes.status >= 400)
    throw new Error(`begin returned HTTP ${beginRes.status}`);
  const loc = beginRes.headers.get("location");
  if (!loc) throw new Error("no Location header on begin redirect");
  const relayState = new URL(loc).searchParams.get("RelayState");
  if (!relayState) throw new Error("no RelayState in redirect");

  // The begin handler persists a SamlStateBag keyed by RelayState; it
  // also chose the AuthnRequest ID for us. Decode that ID from the
  // deflated SAMLRequest so our InResponseTo matches.
  const samlRequestEnc = new URL(loc).searchParams.get("SAMLRequest");
  const { deflateRawSync, inflateRawSync } = await import("node:zlib");
  const authnRequestXml = inflateRawSync(
    Buffer.from(samlRequestEnc, "base64"),
  ).toString("utf8");
  const reqIdMatch = authnRequestXml.match(/ID="([^"]+)"/);
  if (!reqIdMatch) throw new Error("could not find ID in AuthnRequest");
  const requestId = reqIdMatch[1];
  console.log(`  RelayState token: ${relayState.slice(0, 16)}…`);
  console.log(`  Expected InResponseTo: ${requestId}`);

  // 2b. Build + sign the <Response>. Use the ACS URL Hearth advertises
  //     in its SP metadata (act 1) — Destination has to match exactly.
  const responseId = `_r${randomBytes(12).toString("hex")}`;
  const assertionId = `_a${randomBytes(12).toString("hex")}`;
  const acsUrl = acsUrlFromMetadata;
  const spEntityId = acsUrl.replace(/\/federation\/saml\/acs$/, "");
  const unsigned = buildUnsignedResponse({
    responseId,
    assertionId,
    inResponseTo: requestId,
    destination: acsUrl,
    issuer: IDP_ENTITY_ID,
    audience: spEntityId,
    nameId: "alice@example.com",
    sessionIndex: `_s${randomBytes(8).toString("hex")}`,
  });
  const signed = signSamlResponse(
    unsigned,
    privateKeyPem,
    certificatePem,
    responseId,
  );

  // 2c. POST it to the ACS.
  const body = new URLSearchParams({
    SAMLResponse: Buffer.from(signed, "utf8").toString("base64"),
    RelayState: relayState,
  });
  const acsRes = await fetch(acsUrl, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body,
    redirect: "manual",
  });
  if (acsRes.status >= 400) {
    const text = await acsRes.text();
    throw new Error(`ACS returned HTTP ${acsRes.status}: ${text}`);
  }
  console.log(ok(`ACS accepted signed assertion (HTTP ${acsRes.status})`));
  console.log(`  Redirect target: ${acsRes.headers.get("location")}`);

  // 2d. Replay attempt: resubmitting the same assertion must fail.
  const replayBody = new URLSearchParams({
    SAMLResponse: Buffer.from(signed, "utf8").toString("base64"),
    RelayState: relayState,
  });
  const replayRes = await fetch(acsUrl, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: replayBody,
    redirect: "manual",
  });
  if (replayRes.status === 200 || (replayRes.status >= 300 && replayRes.status < 400)) {
    throw new Error(`replay should have been rejected, got ${replayRes.status}`);
  }
  console.log(ok(`replay rejected (HTTP ${replayRes.status})`));
}

// ─── Main ────────────────────────────────────────────────────────────
try {
  const cred = loadIdpCredential();
  const acs = await act1_fetchSpMetadata();
  await act2_postAssertionToAcs(cred, acs);
  console.log(
    "\n\x1b[32mBoth acts completed successfully.\x1b[0m Audit events " +
      "for each act (SamlLoginCompleted, SamlLoginFailed replay) are " +
      "visible via the audit API.",
  );
  process.exit(0);
} catch (err) {
  console.error(`\n\x1b[31m✖\x1b[0m demo failed: ${err.message}`);
  if (process.env.DEBUG) console.error(err.stack);
  process.exit(1);
}
